// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SmalBox {

  /// <summary>Holder for reflection information generated from client.proto</summary>
  public static partial class ClientReflection {

    #region Descriptor
    /// <summary>File descriptor for client.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxjbGllbnQucHJvdG8SCktvbW9yaVRpbWUq0hsKB0NvbW1hbmQSBwoDTmls",
            "EAASHwoYQ01EX0dNQ2hhbmdlQXNzZXRSZXF1ZXN0EMCopQQSIAoZQ01EX0dN",
            "Q2hhbmdlQXNzZXRSZXNwb25zZRDBqKUEEh0KFkNNRF9HTVVubG9ja01hcFJl",
            "cXVlc3QQwqilBBIeChdDTURfR01VbmxvY2tNYXBSZXNwb25zZRDDqKUEEiMK",
            "HENNRF9HTUFkZENvbGxlY3Rpb25MdlJlcXVlc3QQxKilBBIkCh1DTURfR01B",
            "ZGRDb2xsZWN0aW9uTHZSZXNwb25zZRDFqKUEEiIKG0NNRF9HTVNob3djYXNl",
            "QWRkRXhwUmVxdWVzdBDGqKUEEiMKHENNRF9HTVNob3djYXNlQWRkRXhwUmVz",
            "cG9uc2UQx6ilBBIhChpDTURfR01WaXNpdG9yQWRkRXhwUmVxdWVzdBDIqKUE",
            "EiIKG0NNRF9HTVZpc2l0b3JBZGRFeHBSZXNwb25zZRDJqKUEEiIKG0NNRF9H",
            "TVVubG9ja0hhbmRib29rUmVxdWVzdBDKqKUEEiMKHENNRF9HTVVubG9ja0hh",
            "bmRib29rUmVzcG9uc2UQy6ilBBIkCh1DTURfR01VbmxvY2tNdXNldW1BcmVh",
            "UmVxdWVzdBDMqKUEEiUKHkNNRF9HTVVubG9ja011c2V1bUFyZWFSZXNwb25z",
            "ZRDNqKUEEiEKGkNNRF9HbUZpbmlzaE1pc3Npb25SZXF1ZXN0EM6opQQSIgob",
            "Q01EX0dtRmluaXNoTWlzc2lvblJlc3BvbnNlEM+opQQSIgobQ01EX0dNVW5s",
            "b2NrUmVzZWFyY2hSZXF1ZXN0ENCopQQSIwocQ01EX0dNVW5sb2NrUmVzZWFy",
            "Y2hSZXNwb25zZRDRqKUEEiUKHkNNRF9HTVVubG9ja0FsbEhhbmRib29rUmVx",
            "dWVzdBDSqKUEEiYKH0NNRF9HTVVubG9ja0FsbEhhbmRib29rUmVzcG9uc2UQ",
            "06ilBBIjChxDTURfR01Ta2lwTWlzc2lvbkJ5SWRSZXF1ZXN0ENSopQQSJAod",
            "Q01EX0dNU2tpcE1pc3Npb25CeUlkUmVzcG9uc2UQ1ailBBIUChBDTURfTG9n",
            "aW5SZXF1ZXN0EAESFQoRQ01EX0xvZ2luUmVzcG9uc2UQAhIYChRDTURfSGVh",
            "cnRCZWF0UmVxdWVzdBADEhkKFUNNRF9IZWFydEJlYXRSZXNwb25zZRAEEhMK",
            "D0NNRF9UZXN0UmVxdWVzdBAFEhQKEENNRF9UZXN0UmVzcG9uc2UQBhIWChJD",
            "TURfVXNlSXRlbVJlcXVlc3QQFRIXChNDTURfVXNlSXRlbVJlc3BvbnNlEBYS",
            "FgoSQ01EX0l0ZW1DaGFuZ2VQdXNoEBcSGgoWQ01EX1NjZW5lQ2hhbmdlUmVx",
            "dWVzdBAjEhsKF0NNRF9TY2VuZUNoYW5nZVJlc3BvbnNlECQSFwoTQ01EX1Nj",
            "ZW5lVW5sb2NrUHVzaBAlEhcKE0NNRF9GaXNoaW5nSW5mb1B1c2gQKBIbChdD",
            "TURfRmlzaGluZ1N0YXJ0UmVxdWVzdBAtEhwKGENNRF9GaXNoaW5nU3RhcnRS",
            "ZXNwb25zZRAuEhsKF0NNRF9GaXNoaW5nQ2F0Y2hSZXF1ZXN0EC8SHAoYQ01E",
            "X0Zpc2hpbmdDYXRjaFJlc3BvbnNlEDASJAogQ01EX0Zpc2hpbmdSZWZyZXNo",
            "VXNlSXRlbVJlcXVlc3QQMRIlCiFDTURfRmlzaGluZ1JlZnJlc2hVc2VJdGVt",
            "UmVzcG9uc2UQMhIaChZDTURfRmlzaGluZ1JlZnJlc2hQdXNoEDMSFgoSQ01E",
            "X0luc2VjdEluZm9QdXNoEDcSGgoWQ01EX0luc2VjdENhdGNoUmVxdWVzdBA6",
            "EhsKF0NNRF9JbnNlY3RDYXRjaFJlc3BvbnNlEDsSGAoUQ01EX0luc2VjdFFU",
            "RVJlcXVlc3QQPBIZChVDTURfSW5zZWN0UVRFUmVzcG9uc2UQPRIZChVDTURf",
            "SW5zZWN0UmVmcmVzaFB1c2gQPhIfChtDTURfSW5zZWN0Q2hhbmdlVG9vbFJl",
            "cXVlc3QQPxIgChxDTURfSW5zZWN0Q2hhbmdlVG9vbFJlc3BvbnNlEEASGgoW",
            "Q01EX0luc2VjdFN0YXJ0UmVxdWVzdBBBEhsKF0NNRF9JbnNlY3RTdGFydFJl",
            "c3BvbnNlEEISGwoXQ01EX0hhbmRib29rSW5mb1JlcXVlc3QQRxIcChhDTURf",
            "SGFuZGJvb2tJbmZvUmVzcG9uc2UQSBIeChpDTURfSGFuZGJvb2tSZWNlaXZl",
            "UmVxdWVzdBBJEh8KG0NNRF9IYW5kYm9va1JlY2VpdmVSZXNwb25zZRBKEiQK",
            "IENNRF9IYW5kYm9va0NvbGxlY3Rpb25SZXZSZXF1ZXN0EEsSJQohQ01EX0hh",
            "bmRib29rQ29sbGVjdGlvblJldlJlc3BvbnNlEEwSGgoWQ01EX0hhbmRib29r",
            "Q2hhbmdlUHVzaBBNEhsKF0NNRF9NaXNzaW9uUXVlcnlSZXF1ZXN0EFESHAoY",
            "Q01EX01pc3Npb25RdWVyeVJlc3BvbnNlEFISHQoZQ01EX01pc3Npb25SZWNl",
            "aXZlUmVxdWVzdBBTEh4KGkNNRF9NaXNzaW9uUmVjZWl2ZVJlc3BvbnNlEFQS",
            "HAoYQ01EX01pc3Npb25DaGFuZ2VPbmVQdXNoEFUSHAoYQ01EX01pc3Npb25S",
            "ZXdhcmRSZXF1ZXN0EFYSHQoZQ01EX01pc3Npb25SZXdhcmRSZXNwb25zZRBX",
            "Eh0KGUNNRF9NaXNzaW9uQ2hhbmdlTWFueVB1c2gQWBIbChdDTURfRW50ZXJN",
            "dXNldW1JbmZvUHVzaBBbEhwKGENNRF9QbGFjZVNob3djYXNlUmVxdWVzdBBd",
            "Eh0KGUNNRF9QbGFjZVNob3djYXNlUmVzcG9uc2UQXhIbChdDTURfTW92ZVNo",
            "b3djYXNlUmVxdWVzdBBfEhwKGENNRF9Nb3ZlU2hvd2Nhc2VSZXNwb25zZRBg",
            "EhsKF0NNRF9QYWNrU2hvd2Nhc2VSZXF1ZXN0EGESHAoYQ01EX1BhY2tTaG93",
            "Y2FzZVJlc3BvbnNlEGISHAoYQ01EX1BsYWNlRXhoaWJpdHNSZXF1ZXN0EGMS",
            "HQoZQ01EX1BsYWNlRXhoaWJpdHNSZXNwb25zZRBkEhsKF0NNRF9Nb3ZlRXho",
            "aWJpdHNSZXF1ZXN0EGUSHAoYQ01EX01vdmVFeGhpYml0c1Jlc3BvbnNlEGYS",
            "HwobQ01EX1VubG9ja011c2V1bUFyZWFSZXF1ZXN0EGcSIAocQ01EX1VubG9j",
            "a011c2V1bUFyZWFSZXNwb25zZRBoEh8KG0NNRF9NdXNldW1PZmZsaW5lUmV3",
            "YXJkUHVzaBBpEhsKF0NNRF9MZXZlbHVwU2hvd2Nhc2VQdXNoEGoSJAogQ01E",
            "X1JlY2VpdmVTaG93Y2FzZVJld2FyZFJlcXVlc3QQaxIlCiFDTURfUmVjZWl2",
            "ZVNob3djYXNlUmV3YXJkUmVzcG9uc2UQbBIdChlDTURfUmVtb3ZlRXhoaWJp",
            "dHNSZXF1ZXN0EG0SHgoaQ01EX1JlbW92ZUV4aGliaXRzUmVzcG9uc2UQbhIX",
            "ChNDTURfUmVzZWFyY2hSZXF1ZXN0EG8SGAoUQ01EX1Jlc2VhcmNoUmVzcG9u",
            "c2UQcBIfChtDTURfR2V0QWxsUmVzZWFyY2hJZFJlcXVlc3QQcRIgChxDTURf",
            "R2V0QWxsUmVzZWFyY2hJZFJlc3BvbnNlEHISGQoVQ01EX0NyZWF0ZVZpc2l0",
            "b3JQdXNoEHkSHQoZQ01EX0xldmVsdXBWaXNpdG9yUmVxdWVzdBB6Eh4KGkNN",
            "RF9MZXZlbHVwVmlzaXRvclJlc3BvbnNlEHsSIQodQ01EX1Zpc2l0b3JMZWF2",
            "ZU11c2V1bVJlcXVlc3QQfBIiCh5DTURfVmlzaXRvckxlYXZlTXVzZXVtUmVz",
            "cG9uc2UQfRIcChhDTURfVmlzaXRTaG93Y2FzZVJlcXVlc3QQfhIdChlDTURf",
            "VmlzaXRTaG93Y2FzZVJlc3BvbnNlEH8SGgoVQ01EX0dpdmVVcFBhdGhSZXF1",
            "ZXN0EIABEhsKFkNNRF9HaXZlVXBQYXRoUmVzcG9uc2UQgQESHgoZQ01EX0dl",
            "dEFsbFZpc2l0b3JJbmZvUHVzaBCCARIfChpDTURfQ3JlYXRlVmlzaXRvckdy",
            "b3VwUHVzaBCDARIXChJDTURfTnBjVGFsa1JlcXVlc3QQiAESGAoTQ01EX05w",
            "Y1RhbGtSZXNwb25zZRCJARIdChhDTURfUHVyY2hhc2VHb29kc1JlcXVlc3QQ",
            "jQESHgoZQ01EX1B1cmNoYXNlR29vZHNSZXNwb25zZRCOARIfChpDTURfUmVw",
            "bGFjZU5pY2tOYW1lUmVxdWVzdBCSARIgChtDTURfUmVwbGFjZU5pY2tOYW1l",
            "UmVzcG9uc2UQkwESHgoZQ01EX1JlcGxhY2VIZWFkVXJsUmVxdWVzdBCUARIf",
            "ChpDTURfUmVwbGFjZUhlYWRVcmxSZXNwb25zZRCVARIcChdDTURfU3RyZW5n",
            "dGhTeW5jUmVxdWVzdBCXARIdChhDTURfU3RyZW5ndGhTeW5jUmVzcG9uc2UQ",
            "mAESGQoUQ01EX1JlcGFpckJveFJlcXVlc3QQmQESGgoVQ01EX1JlcGFpckJv",
            "eFJlc3BvbnNlEJoBKokMCgdFcnJDb2RlEgsKB1NVQ0NFU1MQABIJCgVFUlJP",
            "UhABEhQKEERBVEFfUVVFUllfRVJST1IQAhISCg5EQVRBX05PVF9GT1VORBAD",
            "EhQKEENPTkZJR19OT1RfRk9VTkQQBBIVChFEQVRBX1VQREFURV9FUlJPUhAF",
            "Eg8KC1BBUkFNX0VSUk9SEAYSEgoOQUREX0lURU1fRVJST1IQBxIaChZVU0VS",
            "X05PVF9BVVRIRU5USUNBVEVEEAgSFQoRTVNHX1VOTUFSU0hBTF9FUlIQCRIQ",
            "CgxNU0dfU0VORF9FUlIQChILCgdVTkRFUl84EAsSHgoaVU5ERVJfMTZfQ0FO",
            "Tk9UX0VYQ0VFRF8yMDAQDBIkCiBVTkRFUl8xNl9TSU5HTEVfQ0FOTk9UX0VY",
            "Q0VFRF81MBANEh4KGlVOREVSXzE4X0NBTk5PVF9FWENFRURfNDAwEA4SJQoh",
            "VU5ERVJfMThfU0lOR0xFX0NBTk5PVF9FWENFRURfMTAwEA8SEwoPSVRFTV9O",
            "T1RfRU5PVUdIEDMSEwoPSVRFTV9BRERfRkFJTEVEEDQSHQoZU0hPV0NBU0Vf",
            "Tk9UX0ZPVU5EX0lOX0JBRxBlEh8KG1NIT1dDQVNFX05PVF9GT1VORF9JTl9T",
            "Q0VORRBmEh8KG1NIT1dDQVNFX0RVUExJQ0FURV9JTl9TQ0VORRBnEhkKFUVY",
            "SElCSVRTX0NBTk5PVF9QTEFDRRBoEiIKHkVYSElCSVRTX05PVF9GT1VORF9J",
            "Tl9TSE9XQ0FTRRBpEhoKFlZJU0lUT1JfRVhQX05PVF9FTk9VR0gQahIdChlW",
            "SVNJVE9SX0FDSElFVkVfTUFYX0xFVkVMEGsSFQoRVklTSVRPUl9OT1RfRk9V",
            "TkQQbBIkCiBFWEhJQklUU19OT1RfRk9VTkRfSU5fQ09MTEVDVElPThBtEhsK",
            "F01VU0VVTV9MRVZFTF9OT1RfRU5PVUdIEG4SFwoTRVhISUJJVFNfTk9UX0VO",
            "T1VHSBBvEg8KC0FSRUFfTE9DS0VEEHASFwoSUkVTRUFSQ0hfRFVQTElDQVRF",
            "EJcBEhQKD1JFU0VBUkNIX0xPQ0tFRBCYARIdChhSRVNFQVJDSF9DT05ESVRJ",
            "T05fRVJST1IQmQESEwoORklTSF9OT1RfRk9VTkQQoAESGAoTRklTSF9BUkVB",
            "X05PVF9GT1VORBChARIXChJGSVNIX1JFRlJFU0hfRVJST1IQogESFwoSRklT",
            "SF9ST0RfTk9UX0VYSVNUEKMBEhYKEUlOU0VDVF9UT09MX0VSUk9SEKUBEhUK",
            "EElOU0VDVF9OT1RfRk9VTkQQpgESGgoVSU5TRUNUX0FSRUFfTk9UX0ZPVU5E",
            "EKcBEhsKFklOU0VDVF9TV0FSTV9OT1RfRk9VTkQQqAESGQoUSU5TRUNUX1JF",
            "RlJFU0hfRVJST1IQqQESGgoVSU5TRUNUX1NXQVJNX0NEX0VSUk9SEKoBEhsK",
            "FkhBTkRCT09LX0xWX05PVF9FTk9VR0gQqwESGwoWSEFOREJPT0tfQUREX0VY",
            "UF9FUlJPUhCsARIYChNIQU5EQk9PS19OT1RfVU5MT0NLEK0BEhsKFkhBTkRC",
            "T09LX05PVF9GT1VORF9FUlIQrgESHQoYSEFOREJPT0tfUkVXQVJEX1JFQ0VJ",
            "VkVEEK8BEhoKFU1JU1NJT05fVFJJR0dFUl9FUlJPUhCwARIcChdNSVNTSU9O",
            "X1JFV0FSRF9SRUNFSVZFRBCxARIWChFNSVNTSU9OX1JFQ19FUlJPUhCyARIZ",
            "ChRNSVNTSU9OX05PVF9GSU5JU0hFRBCzARIZChRNSVNTSU9OX0lEX05PVF9G",
            "T1VORBC0ARIhChxVU0VSX0NIQU5HRV9OQU1FX0lMTEVHQUxfRVJSELoBEhkK",
            "FFVTRVJfTkFNRV9MRU5HVEhfRVJSELsBEhQKD1NDRU5FX05PVF9GT1VORBC/",
            "ARIUCg9TQ0VORV9OT1RfTUFUQ0gQwAESFQoQU0NFTkVfTk9UX1VOTE9DSxDB",
            "ARIbChZDT0xMRUNUSU9OX0JBR19BRERfRVJSEMgBQgtIAVoHbXNnL2NsaWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SmalBox.Command), typeof(global::SmalBox.ErrCode), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Command 分段
  /// client 0-10000
  /// </summary>
  public enum Command {
    [pbr::OriginalName("Nil")] Nil = 0,
    /// <summary>
    ///GM 9000000 ~
    /// </summary>
    [pbr::OriginalName("CMD_GMChangeAssetRequest")] CmdGmchangeAssetRequest = 9000000,
    [pbr::OriginalName("CMD_GMChangeAssetResponse")] CmdGmchangeAssetResponse = 9000001,
    [pbr::OriginalName("CMD_GMUnlockMapRequest")] CmdGmunlockMapRequest = 9000002,
    [pbr::OriginalName("CMD_GMUnlockMapResponse")] CmdGmunlockMapResponse = 9000003,
    [pbr::OriginalName("CMD_GMAddCollectionLvRequest")] CmdGmaddCollectionLvRequest = 9000004,
    [pbr::OriginalName("CMD_GMAddCollectionLvResponse")] CmdGmaddCollectionLvResponse = 9000005,
    [pbr::OriginalName("CMD_GMShowcaseAddExpRequest")] CmdGmshowcaseAddExpRequest = 9000006,
    [pbr::OriginalName("CMD_GMShowcaseAddExpResponse")] CmdGmshowcaseAddExpResponse = 9000007,
    [pbr::OriginalName("CMD_GMVisitorAddExpRequest")] CmdGmvisitorAddExpRequest = 9000008,
    [pbr::OriginalName("CMD_GMVisitorAddExpResponse")] CmdGmvisitorAddExpResponse = 9000009,
    [pbr::OriginalName("CMD_GMUnlockHandbookRequest")] CmdGmunlockHandbookRequest = 9000010,
    [pbr::OriginalName("CMD_GMUnlockHandbookResponse")] CmdGmunlockHandbookResponse = 9000011,
    [pbr::OriginalName("CMD_GMUnlockMuseumAreaRequest")] CmdGmunlockMuseumAreaRequest = 9000012,
    [pbr::OriginalName("CMD_GMUnlockMuseumAreaResponse")] CmdGmunlockMuseumAreaResponse = 9000013,
    [pbr::OriginalName("CMD_GmFinishMissionRequest")] CmdGmFinishMissionRequest = 9000014,
    [pbr::OriginalName("CMD_GmFinishMissionResponse")] CmdGmFinishMissionResponse = 9000015,
    [pbr::OriginalName("CMD_GMUnlockResearchRequest")] CmdGmunlockResearchRequest = 9000016,
    [pbr::OriginalName("CMD_GMUnlockResearchResponse")] CmdGmunlockResearchResponse = 9000017,
    [pbr::OriginalName("CMD_GMUnlockAllHandbookRequest")] CmdGmunlockAllHandbookRequest = 9000018,
    [pbr::OriginalName("CMD_GMUnlockAllHandbookResponse")] CmdGmunlockAllHandbookResponse = 9000019,
    [pbr::OriginalName("CMD_GMSkipMissionByIdRequest")] CmdGmskipMissionByIdRequest = 9000020,
    [pbr::OriginalName("CMD_GMSkipMissionByIdResponse")] CmdGmskipMissionByIdResponse = 9000021,
    /// <summary>
    /// 登录 1 - 10
    /// </summary>
    [pbr::OriginalName("CMD_LoginRequest")] CmdLoginRequest = 1,
    [pbr::OriginalName("CMD_LoginResponse")] CmdLoginResponse = 2,
    /// <summary>
    ///心跳
    /// </summary>
    [pbr::OriginalName("CMD_HeartBeatRequest")] CmdHeartBeatRequest = 3,
    [pbr::OriginalName("CMD_HeartBeatResponse")] CmdHeartBeatResponse = 4,
    [pbr::OriginalName("CMD_TestRequest")] CmdTestRequest = 5,
    [pbr::OriginalName("CMD_TestResponse")] CmdTestResponse = 6,
    /// <summary>
    ///	CMD_OfflineRequest = 5; //client没有主动下线
    ///	CMD_OfflineResponse = 6;
    ///道具 21 - 25
    /// </summary>
    [pbr::OriginalName("CMD_UseItemRequest")] CmdUseItemRequest = 21,
    [pbr::OriginalName("CMD_UseItemResponse")] CmdUseItemResponse = 22,
    [pbr::OriginalName("CMD_ItemChangePush")] CmdItemChangePush = 23,
    /// <summary>
    ///	CMD_ItemInfoPush = 24;
    /// 属性 26 - 30
    ///	CMD_AddAttributeRequest = 26;
    ///	CMD_AddAttributeResponse = 27;
    ///	CMD_AttributeInfoPush = 28;
    ///场景 35-39
    /// </summary>
    [pbr::OriginalName("CMD_SceneChangeRequest")] CmdSceneChangeRequest = 35,
    [pbr::OriginalName("CMD_SceneChangeResponse")] CmdSceneChangeResponse = 36,
    [pbr::OriginalName("CMD_SceneUnlockPush")] CmdSceneUnlockPush = 37,
    /// <summary>
    /// 钓鱼 41 - 50
    /// </summary>
    [pbr::OriginalName("CMD_FishingInfoPush")] CmdFishingInfoPush = 40,
    [pbr::OriginalName("CMD_FishingStartRequest")] CmdFishingStartRequest = 45,
    [pbr::OriginalName("CMD_FishingStartResponse")] CmdFishingStartResponse = 46,
    [pbr::OriginalName("CMD_FishingCatchRequest")] CmdFishingCatchRequest = 47,
    [pbr::OriginalName("CMD_FishingCatchResponse")] CmdFishingCatchResponse = 48,
    [pbr::OriginalName("CMD_FishingRefreshUseItemRequest")] CmdFishingRefreshUseItemRequest = 49,
    [pbr::OriginalName("CMD_FishingRefreshUseItemResponse")] CmdFishingRefreshUseItemResponse = 50,
    [pbr::OriginalName("CMD_FishingRefreshPush")] CmdFishingRefreshPush = 51,
    /// <summary>
    /// 捕虫 55 - 70
    /// </summary>
    [pbr::OriginalName("CMD_InsectInfoPush")] CmdInsectInfoPush = 55,
    [pbr::OriginalName("CMD_InsectCatchRequest")] CmdInsectCatchRequest = 58,
    [pbr::OriginalName("CMD_InsectCatchResponse")] CmdInsectCatchResponse = 59,
    [pbr::OriginalName("CMD_InsectQTERequest")] CmdInsectQterequest = 60,
    [pbr::OriginalName("CMD_InsectQTEResponse")] CmdInsectQteresponse = 61,
    [pbr::OriginalName("CMD_InsectRefreshPush")] CmdInsectRefreshPush = 62,
    [pbr::OriginalName("CMD_InsectChangeToolRequest")] CmdInsectChangeToolRequest = 63,
    [pbr::OriginalName("CMD_InsectChangeToolResponse")] CmdInsectChangeToolResponse = 64,
    [pbr::OriginalName("CMD_InsectStartRequest")] CmdInsectStartRequest = 65,
    [pbr::OriginalName("CMD_InsectStartResponse")] CmdInsectStartResponse = 66,
    /// <summary>
    /// 图鉴 71-80
    /// </summary>
    [pbr::OriginalName("CMD_HandbookInfoRequest")] CmdHandbookInfoRequest = 71,
    [pbr::OriginalName("CMD_HandbookInfoResponse")] CmdHandbookInfoResponse = 72,
    [pbr::OriginalName("CMD_HandbookReceiveRequest")] CmdHandbookReceiveRequest = 73,
    [pbr::OriginalName("CMD_HandbookReceiveResponse")] CmdHandbookReceiveResponse = 74,
    [pbr::OriginalName("CMD_HandbookCollectionRevRequest")] CmdHandbookCollectionRevRequest = 75,
    [pbr::OriginalName("CMD_HandbookCollectionRevResponse")] CmdHandbookCollectionRevResponse = 76,
    [pbr::OriginalName("CMD_HandbookChangePush")] CmdHandbookChangePush = 77,
    /// <summary>
    /// 任务模块 81 - 90
    /// </summary>
    [pbr::OriginalName("CMD_MissionQueryRequest")] CmdMissionQueryRequest = 81,
    [pbr::OriginalName("CMD_MissionQueryResponse")] CmdMissionQueryResponse = 82,
    [pbr::OriginalName("CMD_MissionReceiveRequest")] CmdMissionReceiveRequest = 83,
    [pbr::OriginalName("CMD_MissionReceiveResponse")] CmdMissionReceiveResponse = 84,
    [pbr::OriginalName("CMD_MissionChangeOnePush")] CmdMissionChangeOnePush = 85,
    [pbr::OriginalName("CMD_MissionRewardRequest")] CmdMissionRewardRequest = 86,
    [pbr::OriginalName("CMD_MissionRewardResponse")] CmdMissionRewardResponse = 87,
    [pbr::OriginalName("CMD_MissionChangeManyPush")] CmdMissionChangeManyPush = 88,
    /// <summary>
    /// 博物馆 91 - 110
    /// </summary>
    [pbr::OriginalName("CMD_EnterMuseumInfoPush")] CmdEnterMuseumInfoPush = 91,
    [pbr::OriginalName("CMD_PlaceShowcaseRequest")] CmdPlaceShowcaseRequest = 93,
    [pbr::OriginalName("CMD_PlaceShowcaseResponse")] CmdPlaceShowcaseResponse = 94,
    [pbr::OriginalName("CMD_MoveShowcaseRequest")] CmdMoveShowcaseRequest = 95,
    [pbr::OriginalName("CMD_MoveShowcaseResponse")] CmdMoveShowcaseResponse = 96,
    [pbr::OriginalName("CMD_PackShowcaseRequest")] CmdPackShowcaseRequest = 97,
    [pbr::OriginalName("CMD_PackShowcaseResponse")] CmdPackShowcaseResponse = 98,
    [pbr::OriginalName("CMD_PlaceExhibitsRequest")] CmdPlaceExhibitsRequest = 99,
    [pbr::OriginalName("CMD_PlaceExhibitsResponse")] CmdPlaceExhibitsResponse = 100,
    [pbr::OriginalName("CMD_MoveExhibitsRequest")] CmdMoveExhibitsRequest = 101,
    [pbr::OriginalName("CMD_MoveExhibitsResponse")] CmdMoveExhibitsResponse = 102,
    [pbr::OriginalName("CMD_UnlockMuseumAreaRequest")] CmdUnlockMuseumAreaRequest = 103,
    [pbr::OriginalName("CMD_UnlockMuseumAreaResponse")] CmdUnlockMuseumAreaResponse = 104,
    [pbr::OriginalName("CMD_MuseumOfflineRewardPush")] CmdMuseumOfflineRewardPush = 105,
    [pbr::OriginalName("CMD_LevelupShowcasePush")] CmdLevelupShowcasePush = 106,
    [pbr::OriginalName("CMD_ReceiveShowcaseRewardRequest")] CmdReceiveShowcaseRewardRequest = 107,
    [pbr::OriginalName("CMD_ReceiveShowcaseRewardResponse")] CmdReceiveShowcaseRewardResponse = 108,
    [pbr::OriginalName("CMD_RemoveExhibitsRequest")] CmdRemoveExhibitsRequest = 109,
    [pbr::OriginalName("CMD_RemoveExhibitsResponse")] CmdRemoveExhibitsResponse = 110,
    /// <summary>
    /// 研究  111 - 120
    /// </summary>
    [pbr::OriginalName("CMD_ResearchRequest")] CmdResearchRequest = 111,
    [pbr::OriginalName("CMD_ResearchResponse")] CmdResearchResponse = 112,
    [pbr::OriginalName("CMD_GetAllResearchIdRequest")] CmdGetAllResearchIdRequest = 113,
    [pbr::OriginalName("CMD_GetAllResearchIdResponse")] CmdGetAllResearchIdResponse = 114,
    /// <summary>
    /// 游客系统 121 - 135
    /// </summary>
    [pbr::OriginalName("CMD_CreateVisitorPush")] CmdCreateVisitorPush = 121,
    [pbr::OriginalName("CMD_LevelupVisitorRequest")] CmdLevelupVisitorRequest = 122,
    [pbr::OriginalName("CMD_LevelupVisitorResponse")] CmdLevelupVisitorResponse = 123,
    [pbr::OriginalName("CMD_VisitorLeaveMuseumRequest")] CmdVisitorLeaveMuseumRequest = 124,
    [pbr::OriginalName("CMD_VisitorLeaveMuseumResponse")] CmdVisitorLeaveMuseumResponse = 125,
    [pbr::OriginalName("CMD_VisitShowcaseRequest")] CmdVisitShowcaseRequest = 126,
    [pbr::OriginalName("CMD_VisitShowcaseResponse")] CmdVisitShowcaseResponse = 127,
    [pbr::OriginalName("CMD_GiveUpPathRequest")] CmdGiveUpPathRequest = 128,
    [pbr::OriginalName("CMD_GiveUpPathResponse")] CmdGiveUpPathResponse = 129,
    [pbr::OriginalName("CMD_GetAllVisitorInfoPush")] CmdGetAllVisitorInfoPush = 130,
    [pbr::OriginalName("CMD_CreateVisitorGroupPush")] CmdCreateVisitorGroupPush = 131,
    /// <summary>
    /// NPC 对话 136 - 137
    /// </summary>
    [pbr::OriginalName("CMD_NpcTalkRequest")] CmdNpcTalkRequest = 136,
    [pbr::OriginalName("CMD_NpcTalkResponse")] CmdNpcTalkResponse = 137,
    /// <summary>
    ///141-145 商城
    /// </summary>
    [pbr::OriginalName("CMD_PurchaseGoodsRequest")] CmdPurchaseGoodsRequest = 141,
    [pbr::OriginalName("CMD_PurchaseGoodsResponse")] CmdPurchaseGoodsResponse = 142,
    /// <summary>
    ///146-150 变更用户信息
    /// </summary>
    [pbr::OriginalName("CMD_ReplaceNickNameRequest")] CmdReplaceNickNameRequest = 146,
    [pbr::OriginalName("CMD_ReplaceNickNameResponse")] CmdReplaceNickNameResponse = 147,
    [pbr::OriginalName("CMD_ReplaceHeadUrlRequest")] CmdReplaceHeadUrlRequest = 148,
    [pbr::OriginalName("CMD_ReplaceHeadUrlResponse")] CmdReplaceHeadUrlResponse = 149,
    /// <summary>
    ///151 - 155 体力同步
    /// </summary>
    [pbr::OriginalName("CMD_StrengthSyncRequest")] CmdStrengthSyncRequest = 151,
    [pbr::OriginalName("CMD_StrengthSyncResponse")] CmdStrengthSyncResponse = 152,
    /// <summary>
    ///151-155 博物馆宝箱
    /// </summary>
    [pbr::OriginalName("CMD_RepairBoxRequest")] CmdRepairBoxRequest = 153,
    [pbr::OriginalName("CMD_RepairBoxResponse")] CmdRepairBoxResponse = 154,
  }

  /// <summary>
  /// 错误码
  /// </summary>
  public enum ErrCode {
    /// <summary>
    ///0 成功
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    ///1-50 服务器系统错误
    /// </summary>
    [pbr::OriginalName("ERROR")] Error = 1,
    /// <summary>
    ///数据查询错误
    /// </summary>
    [pbr::OriginalName("DATA_QUERY_ERROR")] DataQueryError = 2,
    /// <summary>
    ///找不到对应数据
    /// </summary>
    [pbr::OriginalName("DATA_NOT_FOUND")] DataNotFound = 3,
    /// <summary>
    ///找不到对用配置
    /// </summary>
    [pbr::OriginalName("CONFIG_NOT_FOUND")] ConfigNotFound = 4,
    /// <summary>
    ///数据修改错误
    /// </summary>
    [pbr::OriginalName("DATA_UPDATE_ERROR")] DataUpdateError = 5,
    /// <summary>
    ///参数错误
    /// </summary>
    [pbr::OriginalName("PARAM_ERROR")] ParamError = 6,
    /// <summary>
    ///添加道具错误
    /// </summary>
    [pbr::OriginalName("ADD_ITEM_ERROR")] AddItemError = 7,
    /// <summary>
    ///用户未验证
    /// </summary>
    [pbr::OriginalName("USER_NOT_AUTHENTICATED")] UserNotAuthenticated = 8,
    /// <summary>
    ///消息解析错误
    /// </summary>
    [pbr::OriginalName("MSG_UNMARSHAL_ERR")] MsgUnmarshalErr = 9,
    /// <summary>
    ///消息发送错误
    /// </summary>
    [pbr::OriginalName("MSG_SEND_ERR")] MsgSendErr = 10,
    /// <summary>
    ///未满8周岁不能充值
    /// </summary>
    [pbr::OriginalName("UNDER_8")] Under8 = 11,
    /// <summary>
    ///未满16周岁充值不能超过200
    /// </summary>
    [pbr::OriginalName("UNDER_16_CANNOT_EXCEED_200")] Under16CannotExceed200 = 12,
    /// <summary>
    ///未满16周岁单次充值不能超过50
    /// </summary>
    [pbr::OriginalName("UNDER_16_SINGLE_CANNOT_EXCEED_50")] Under16SingleCannotExceed50 = 13,
    /// <summary>
    ///未满18周岁单次充值不能超过400
    /// </summary>
    [pbr::OriginalName("UNDER_18_CANNOT_EXCEED_400")] Under18CannotExceed400 = 14,
    /// <summary>
    ///未满18周岁单次充值不能超过100
    /// </summary>
    [pbr::OriginalName("UNDER_18_SINGLE_CANNOT_EXCEED_100")] Under18SingleCannotExceed100 = 15,
    /// <summary>
    ///51 - 100 道具错误
    /// </summary>
    [pbr::OriginalName("ITEM_NOT_ENOUGH")] ItemNotEnough = 51,
    /// <summary>
    ///道具添加失败
    /// </summary>
    [pbr::OriginalName("ITEM_ADD_FAILED")] ItemAddFailed = 52,
    /// <summary>
    ///101 - 150 博物馆错误
    /// </summary>
    [pbr::OriginalName("SHOWCASE_NOT_FOUND_IN_BAG")] ShowcaseNotFoundInBag = 101,
    /// <summary>
    ///场景找不到对应展柜
    /// </summary>
    [pbr::OriginalName("SHOWCASE_NOT_FOUND_IN_SCENE")] ShowcaseNotFoundInScene = 102,
    /// <summary>
    ///场景出现重复展柜
    /// </summary>
    [pbr::OriginalName("SHOWCASE_DUPLICATE_IN_SCENE")] ShowcaseDuplicateInScene = 103,
    /// <summary>
    ///展品不可被放置
    /// </summary>
    [pbr::OriginalName("EXHIBITS_CANNOT_PLACE")] ExhibitsCannotPlace = 104,
    /// <summary>
    ///未能在展柜指定位置找到展品
    /// </summary>
    [pbr::OriginalName("EXHIBITS_NOT_FOUND_IN_SHOWCASE")] ExhibitsNotFoundInShowcase = 105,
    /// <summary>
    ///游客经验不足
    /// </summary>
    [pbr::OriginalName("VISITOR_EXP_NOT_ENOUGH")] VisitorExpNotEnough = 106,
    /// <summary>
    ///游客达到最大等级
    /// </summary>
    [pbr::OriginalName("VISITOR_ACHIEVE_MAX_LEVEL")] VisitorAchieveMaxLevel = 107,
    /// <summary>
    ///未能找到指定游客
    /// </summary>
    [pbr::OriginalName("VISITOR_NOT_FOUND")] VisitorNotFound = 108,
    /// <summary>
    ///未能在收集物品中找到指定展品
    /// </summary>
    [pbr::OriginalName("EXHIBITS_NOT_FOUND_IN_COLLECTION")] ExhibitsNotFoundInCollection = 109,
    /// <summary>
    ///博物馆等级不足
    /// </summary>
    [pbr::OriginalName("MUSEUM_LEVEL_NOT_ENOUGH")] MuseumLevelNotEnough = 110,
    /// <summary>
    ///展品数量不足
    /// </summary>
    [pbr::OriginalName("EXHIBITS_NOT_ENOUGH")] ExhibitsNotEnough = 111,
    /// <summary>
    ///区域未解锁
    /// </summary>
    [pbr::OriginalName("AREA_LOCKED")] AreaLocked = 112,
    /// <summary>
    ///151 - 155 研究错误
    /// </summary>
    [pbr::OriginalName("RESEARCH_DUPLICATE")] ResearchDuplicate = 151,
    /// <summary>
    ///研究未解锁
    /// </summary>
    [pbr::OriginalName("RESEARCH_LOCKED")] ResearchLocked = 152,
    /// <summary>
    ///研究条件未达成
    /// </summary>
    [pbr::OriginalName("RESEARCH_CONDITION_ERROR")] ResearchConditionError = 153,
    /// <summary>
    ///160 - 164 鱼
    /// </summary>
    [pbr::OriginalName("FISH_NOT_FOUND")] FishNotFound = 160,
    /// <summary>
    ///鱼塘区域不存在
    /// </summary>
    [pbr::OriginalName("FISH_AREA_NOT_FOUND")] FishAreaNotFound = 161,
    /// <summary>
    ///刷鱼失败
    /// </summary>
    [pbr::OriginalName("FISH_REFRESH_ERROR")] FishRefreshError = 162,
    /// <summary>
    ///鱼竿不存在
    /// </summary>
    [pbr::OriginalName("FISH_ROD_NOT_EXIST")] FishRodNotExist = 163,
    /// <summary>
    ///165 - 170 捕虫
    /// </summary>
    [pbr::OriginalName("INSECT_TOOL_ERROR")] InsectToolError = 165,
    /// <summary>
    ///找不到虫
    /// </summary>
    [pbr::OriginalName("INSECT_NOT_FOUND")] InsectNotFound = 166,
    /// <summary>
    ///找不到捕虫区域
    /// </summary>
    [pbr::OriginalName("INSECT_AREA_NOT_FOUND")] InsectAreaNotFound = 167,
    /// <summary>
    ///找不到虫群
    /// </summary>
    [pbr::OriginalName("INSECT_SWARM_NOT_FOUND")] InsectSwarmNotFound = 168,
    /// <summary>
    ///刷新虫失败
    /// </summary>
    [pbr::OriginalName("INSECT_REFRESH_ERROR")] InsectRefreshError = 169,
    /// <summary>
    ///虫群还在CD中
    /// </summary>
    [pbr::OriginalName("INSECT_SWARM_CD_ERROR")] InsectSwarmCdError = 170,
    /// <summary>
    ///171 - 175 博物馆图鉴
    /// </summary>
    [pbr::OriginalName("HANDBOOK_LV_NOT_ENOUGH")] HandbookLvNotEnough = 171,
    /// <summary>
    ///增加图鉴 经验错误
    /// </summary>
    [pbr::OriginalName("HANDBOOK_ADD_EXP_ERROR")] HandbookAddExpError = 172,
    /// <summary>
    ///图鉴未解锁
    /// </summary>
    [pbr::OriginalName("HANDBOOK_NOT_UNLOCK")] HandbookNotUnlock = 173,
    /// <summary>
    ///图鉴找不到
    /// </summary>
    [pbr::OriginalName("HANDBOOK_NOT_FOUND_ERR")] HandbookNotFoundErr = 174,
    /// <summary>
    ///奖励已领取
    /// </summary>
    [pbr::OriginalName("HANDBOOK_REWARD_RECEIVED")] HandbookRewardReceived = 175,
    /// <summary>
    ///176 - 185 任务
    /// </summary>
    [pbr::OriginalName("MISSION_TRIGGER_ERROR")] MissionTriggerError = 176,
    /// <summary>
    ///任务奖励已领取
    /// </summary>
    [pbr::OriginalName("MISSION_REWARD_RECEIVED")] MissionRewardReceived = 177,
    /// <summary>
    ///任务领取错误
    /// </summary>
    [pbr::OriginalName("MISSION_REC_ERROR")] MissionRecError = 178,
    /// <summary>
    ///任务未完成
    /// </summary>
    [pbr::OriginalName("MISSION_NOT_FINISHED")] MissionNotFinished = 179,
    /// <summary>
    ///任务ID找不到
    /// </summary>
    [pbr::OriginalName("MISSION_ID_NOT_FOUND")] MissionIdNotFound = 180,
    /// <summary>
    ///186 - 190 用户信息变更
    /// </summary>
    [pbr::OriginalName("USER_CHANGE_NAME_ILLEGAL_ERR")] UserChangeNameIllegalErr = 186,
    /// <summary>
    ///名称长度过长
    /// </summary>
    [pbr::OriginalName("USER_NAME_LENGTH_ERR")] UserNameLengthErr = 187,
    /// <summary>
    ///191 - 195 场景
    /// </summary>
    [pbr::OriginalName("SCENE_NOT_FOUND")] SceneNotFound = 191,
    /// <summary>
    ///场景不匹配
    /// </summary>
    [pbr::OriginalName("SCENE_NOT_MATCH")] SceneNotMatch = 192,
    /// <summary>
    ///场景未解锁
    /// </summary>
    [pbr::OriginalName("SCENE_NOT_UNLOCK")] SceneNotUnlock = 193,
    /// <summary>
    ///200
    /// </summary>
    [pbr::OriginalName("COLLECTION_BAG_ADD_ERR")] CollectionBagAddErr = 200,
  }

  #endregion

}

#endregion Designer generated code
